<a href="https://colab.research.google.com/github/LandonTeeter/bashing/blob/main/Projects/Project%201_save.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Take-home project 1

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/nekrut/bda/blob/main/Projects/Project%201.ipynb)

Write your PSU email address here:lzt5326@psu.edu

Share the notebook with aun1@psu.edu

## Summary:

### Q&A
The visualization shows that Pyrimethamine resistance allele frequencies are very high in both Colombia and Ivory Coast. In Colombia, the resistance allele frequency is 95.7%, with 4.3% non-resistance. In Ivory Coast, the resistance allele frequency is even higher at 99.1%, with 0.9% non-resistance. This indicates a widespread presence of Pyrimethamine resistance in both regions.

### Data Analysis Key Findings
*   Geographical coordinates for Ivory Coast (latitude: 7.54, longitude: -5.55) and Colombia (latitude: 4.57, longitude: -74.30) were successfully prepared and stored in a DataFrame.
*   The maximum Pyrimethamine resistance allele frequency (AF) for Colombia was calculated as 0.957143, with a non-resistance AF of 0.042857.
*   For Ivory Coast, the maximum Pyrimethamine resistance allele frequency was 0.991416, with a non-resistance AF of 0.008584.
*   A world map was successfully generated using Altair, featuring overlaid pie charts at the respective geographical coordinates for Colombia and Ivory Coast. These pie charts visually represent the proportion of resistance versus non-resistance allele frequencies, using red for resistance and blue for non-resistance, with their sizes reflecting the frequencies.

### Insights or Next Steps
*   The extremely high Pyrimethamine resistance allele frequencies in both Colombia (~95.7%) and Ivory Coast (~99.1%) suggest that Pyrimethamine, as a standalone treatment for malaria, may have significantly reduced efficacy in these regions.
*   Further research should investigate the specific mutations contributing to resistance in these locations and explore alternative or combination therapies for malaria treatment in these high-resistance areas.


## Load the data

In [2]:
import pandas as pd

variants = pd.read_csv(
    "https://raw.githubusercontent.com/nekrut/bda/main/data/pf_variants.tsv",
    sep="\t"
)

variants.head()

Sample        CHROM     POS REF ALT    QUAL  DP        AF  SB  \
0  ERR042228.fq  NC_004318.2  657697   T   C   324.0  14  0.857143   0   
1  ERR042228.fq  NC_004318.2  658447   A   G   453.0  32  0.718750  11   
2  ERR042228.fq  NC_004318.2  659163   C   A  1928.0  56  0.982143   0   
3  ERR042228.fq  NC_004318.2  659167   C   T  1887.0  56  0.964286   0   
4  ERR042228.fq  NC_004318.2  660292   T   C   104.0  34  0.176471   0   

         DP4             EFFECT    IMPACT                         GENE  \
0   1,0,13,0  intergenic_region  MODIFIER  PF3D7_0414500-PF3D7_0414600   
1  5,1,10,16  intergenic_region  MODIFIER  PF3D7_0414500-PF3D7_0414600   
2  0,0,21,35   missense_variant  MODERATE                PF3D7_0414600   
3  0,0,21,35   missense_variant  MODERATE                PF3D7_0414600   
4    6,8,2,4  intergenic_region  MODIFIER  PF3D7_0414600-PF3D7_0414700   

   AA_POS       HGVS_C      HGVS_P  
0      -1  n.657697T>C         NaN  
1      -1  n.658447A>G         NaN  
2      55     c.165G>T  p.Glu55Asp  
3      54     c.161G>A  p.Cys54Tyr  
4      -1  n.660292T>C         NaN

## Instructions

Our goal is to understand whether the malaria parasite ([*Plasmodium falciparum*](https://brc-analytics.dev.clevercanary.com/data/organisms/5833)) infecting these individuals is resistant to [Pyrimethamine](https://en.wikipedia.org/wiki/Pyrimethamine)---an antimalarial drug. Resistance to Pyrimethamine is conferred by a mutation in `PF3D7_0417200` (*dhfr*) gene [Cowman1988](https://doi.org/10.1073/pnas.85.23.9109). Given sequencing data from four individuals we will determine which one of them is infected with a *Plasmodium falciparum* carrying mutations in this gene.

Variant calls in the provided Pandas data frame represent analysis of four samples: two from Ivory Coast and two from Colombia:

| Accession | Location |
|------------|------------|
| [ERR636434](https://www.ncbi.nlm.nih.gov/sra/?term=ERR636434) | Ivory coast |
| [ERR636028](https://www.ncbi.nlm.nih.gov/sra/?term=ERR636028) | Ivory coast |
| [ERR042232](https://www.ncbi.nlm.nih.gov/sra/?term=ERR042232) | Colombia |
| [ERR042228](https://www.ncbi.nlm.nih.gov/sra/?term=ERR042228) | Colombia |

These accessions correspond to datasets stored in the [Sequence Read Archive](https://www.ncbi.nlm.nih.gov/sra) at NCBI.

(data from [MalariaGen](https://www.malariagen.net/data_package/open-dataset-plasmodium-falciparum-v70/) )

## Specifics

- Filter variants falling within the *dhfr* gene
- Restrict variants to missense variants only using the effect column.
- You are specifically interested in variant at amino acid position 108
- Create a graph that shows samples vs variant coordinates, in which graph marks are proportional to alternative allele frequencies (**AF** column)
- Create a graph showing a world map in which allele frequencies of these two samples are represented as pie charts within the map of Colombia and within the map of Ivory Coast.  to be more specific, for each location you have two samples. Each of these samples will have an allele frequency at the resistance side. Use these allele frequencies as areas on the pie chart

> You can use any AI you want (preferably the one integrated in Colab) but you will never get exactly what you want, so you will have to adjust it. You will have to explain to me what the steps were.


In [3]:
dhfr_variants = variants[variants['GENE'].str.contains('PF3D7_0417200')]
display(dhfr_variants.head())

Sample        CHROM     POS REF ALT    QUAL   DP        AF  SB  \
147  ERR042228.fq  NC_004318.2  748410   G   A  2335.0   70  0.957143   0   
486  ERR042232.fq  NC_004318.2  747426   G   A    74.0   12  0.333333   0   
826  ERR636028.fq  NC_004318.2  747426   G   A   147.0   41  0.219512   3   
827  ERR636028.fq  NC_004318.2  747682   G   A   166.0   26  0.269231   3   
828  ERR636028.fq  NC_004318.2  748239   A   T  6941.0  194  0.984536   0   

            DP4             EFFECT    IMPACT                         GENE  \
147   0,0,30,40   missense_variant  MODERATE                PF3D7_0417200   
486     1,5,0,6  intergenic_region  MODIFIER  PF3D7_0417100-PF3D7_0417200   
826   5,10,5,19  intergenic_region  MODIFIER  PF3D7_0417100-PF3D7_0417200   
827    1,1,5,15  intergenic_region  MODIFIER  PF3D7_0417100-PF3D7_0417200   
828  0,0,117,77   missense_variant  MODERATE                PF3D7_0417200   

     AA_POS       HGVS_C       HGVS_P  
147     108     c.323G>A  p.Ser108Asn  
486      -1  n.747426G>A          NaN  
826      -1  n.747426G>A          NaN  
827      -1  n.747682G>A          NaN  
828      51     c.152A>T   p.Asn51Ile

In [4]:
dhfr_missense_variants = dhfr_variants[dhfr_variants['EFFECT'] == 'missense_variant']
display(dhfr_missense_variants.head())

Sample        CHROM     POS REF ALT    QUAL   DP        AF  SB  \
147   ERR042228.fq  NC_004318.2  748410   G   A  2335.0   70  0.957143   0   
828   ERR636028.fq  NC_004318.2  748239   A   T  6941.0  194  0.984536   0   
829   ERR636028.fq  NC_004318.2  748262   T   C  7627.0  211  0.981043   0   
830   ERR636028.fq  NC_004318.2  748410   G   A  8292.0  233  0.991416   0   
1242  ERR636434.fq  NC_004318.2  748262   T   C    67.0  214  0.018692   0   

              DP4            EFFECT    IMPACT           GENE  AA_POS  \
147     0,0,30,40  missense_variant  MODERATE  PF3D7_0417200     108   
828    0,0,117,77  missense_variant  MODERATE  PF3D7_0417200      51   
829    0,0,117,93  missense_variant  MODERATE  PF3D7_0417200      59   
830   0,0,112,121  missense_variant  MODERATE  PF3D7_0417200     108   
1242   113,97,2,2  missense_variant  MODERATE  PF3D7_0417200      59   

        HGVS_C       HGVS_P  
147   c.323G>A  p.Ser108Asn  
828   c.152A>T   p.Asn51Ile  
829   c.175T>C   p.Cys59Arg  
830   c.323G>A  p.Ser108Asn  
1242  c.175T>C   p.Cys59Arg

In [5]:
import altair as alt

dhfr_108_variants = dhfr_missense_variants[dhfr_missense_variants['AA_POS'] == 108]
display(dhfr_108_variants.head())

Sample        CHROM     POS REF ALT    QUAL   DP        AF  SB  \
147  ERR042228.fq  NC_004318.2  748410   G   A  2335.0   70  0.957143   0   
830  ERR636028.fq  NC_004318.2  748410   G   A  8292.0  233  0.991416   0   

             DP4            EFFECT    IMPACT           GENE  AA_POS    HGVS_C  \
147    0,0,30,40  missense_variant  MODERATE  PF3D7_0417200     108  c.323G>A   
830  0,0,112,121  missense_variant  MODERATE  PF3D7_0417200     108  c.323G>A   

          HGVS_P  
147  p.Ser108Asn  
830  p.Ser108Asn

In [6]:
# Normalize Sample names by removing '.fq' suffix for consistency
dhfr_108_variants_normalized = dhfr_108_variants.copy()
dhfr_108_variants_normalized['Sample'] = dhfr_108_variants_normalized['Sample'].str.replace('.fq', '', regex=False)

# Create a list to store data for the scatter plot, including reference alleles
scatter_plot_rows = []

# Iterate through each unique sample to ensure all four samples are represented
# This also handles cases where a sample might not have the specific variant
# but we still want to show its reference state.
all_samples = ['ERR636434', 'ERR636028', 'ERR042232', 'ERR042228']

# Define the reference position and alleles
reference_chrom = 'NC_004318.2'
reference_pos = 748410
original_ref_allele = 'G'
reference_hgvs_p = 'p.Ser108'

for sample in all_samples:
    sample_variants = dhfr_108_variants_normalized[dhfr_108_variants_normalized['Sample'] == sample]

    if not sample_variants.empty:
        # If the sample has a variant at this position
        for index, row in sample_variants.iterrows():
            scatter_plot_rows.append({
                'Sample': row['Sample'],
                'POS': row['POS'],
                'AF': row['AF'],
                'CHROM': row['CHROM'],
                'REF': row['REF'],
                'ALT': row['ALT'],
                'HGVS_P': row['HGVS_P']
            })
    else:
        # If the sample does not have a variant, assume reference allele with AF=0
        scatter_plot_rows.append({
            'Sample': sample,
            'POS': reference_pos,
            'AF': 0.0,
            'CHROM': reference_chrom,
            'REF': original_ref_allele,
            'ALT': original_ref_allele,
            'HGVS_P': reference_hgvs_p # Assuming 'Ser108' as the reference amino acid
        })

scatter_plot_data = pd.DataFrame(scatter_plot_rows)
display(scatter_plot_data)

# Create the scatter plot using Altair, with color encoding for AF
chart = alt.Chart(scatter_plot_data).mark_point().encode(
    x=alt.X('POS', title='Variant Coordinate (POS)'),
    y=alt.Y('Sample', title='Sample Accession'),
    fill=alt.Color('AF', title='Alternative Allele Frequency', legend=alt.Legend(format='.0%'), scale=alt.Scale(scheme='redblue')),
    stroke=alt.value('black'),
    strokeWidth=alt.value(1),
    tooltip=[
        alt.Tooltip('Sample'),
        alt.Tooltip('CHROM', title='Chromosome'),
        alt.Tooltip('POS', title='Position'),
        alt.Tooltip('REF', title='Reference Allele'),
        alt.Tooltip('ALT', title='Alternative Allele'),
        alt.Tooltip('AF', title='Allele Frequency', format='.2%'),
        alt.Tooltip('HGVS_P', title='Protein Change')
    ]
).properties(
    title='Allele Frequencies of dhfr gene variants at AA Position 108'
)

chart.display()

Sample     POS        AF        CHROM REF ALT       HGVS_P
0  ERR636434  748410  0.000000  NC_004318.2   G   G     p.Ser108
1  ERR636028  748410  0.991416  NC_004318.2   G   A  p.Ser108Asn
2  ERR042232  748410  0.000000  NC_004318.2   G   G     p.Ser108
3  ERR042228  748410  0.957143  NC_004318.2   G   A  p.Ser108Asn

alt.Chart(...)

# Task
Generate a world map using Altair, featuring overlaid pie charts at the geographical coordinates of Colombia and Ivory Coast. Each pie chart should represent the aggregated allele frequencies for Pyrimethamine resistance for its respective country: one slice for the resistance allele frequency (taking the maximum non-zero AF from the samples for that location) and the other for the non-resistance frequency (1 - resistance AF). The size of the pie slices should be proportional to these frequencies, and distinct colors should differentiate between resistance and non-resistance, with appropriate legends for clarity.

## Prepare Geographical Data

### Subtask:
Define a DataFrame with the geographical coordinates for Ivory Coast and Colombia. This will serve as the base for positioning the pie charts on the map.


**Reasoning**:
I will create a dictionary with the specified geographical coordinates for Ivory Coast and Colombia and then convert it into a Pandas DataFrame to fulfill the subtask requirement.



In [27]:
location_coords = {
    'Ivory Coast': {'lat': 7.54, 'lon': -5.55}, # Close to actual center of Ivory Coast
    'Colombia': {'lat': 4.57, 'lon': -74.30} # Corrected latitude and longitude for Colombia
}

# Convert the dictionary to a DataFrame
location_df = pd.DataFrame.from_dict(location_coords, orient='index')
location_df = location_df.reset_index().rename(columns={'index': 'Country'})

display(location_df)

Country   lat    lon
0  Ivory Coast  7.54  -5.55
1     Colombia  4.57 -74.30

In [28]:
sample_to_country = {
    'ERR636434': 'Ivory Coast',
    'ERR636028': 'Ivory Coast',
    'ERR042232': 'Colombia',
    'ERR042228': 'Colombia'
}

scatter_plot_data_merged = scatter_plot_data.copy()
scatter_plot_data_merged['Country'] = scatter_plot_data_merged['Sample'].map(sample_to_country)
display(scatter_plot_data_merged.head())

Sample     POS        AF        CHROM REF ALT       HGVS_P      Country
0  ERR636434  748410  0.000000  NC_004318.2   G   G     p.Ser108  Ivory Coast
1  ERR636028  748410  0.991416  NC_004318.2   G   A  p.Ser108Asn  Ivory Coast
2  ERR042232  748410  0.000000  NC_004318.2   G   G     p.Ser108     Colombia
3  ERR042228  748410  0.957143  NC_004318.2   G   A  p.Ser108Asn     Colombia

In [29]:
import altair as alt
alt.data_transformers.disable_max_rows()

# Load the world map data using alt.topo_feature
world_map = alt.topo_feature(
    url='https://raw.githubusercontent.com/vega/vega-datasets/next/data/world-110m.json',
    feature='countries'
)

# Create the base map with adjusted scale and center for desired view
base_map = alt.Chart(world_map).mark_geoshape(stroke='black', strokeWidth=0.15).project(
    'mercator', scale=200, center=[-39.925, 6.055] # Scale to 100 as requested, centered between Colombia and Ivory Coast
)

# Create the pie chart arcs (significantly smaller outerRadius)
pie_arcs = alt.Chart(pie_chart_data_final).mark_arc(outerRadius=8).encode(
    theta=alt.Theta("frequency", stack=True),
    color=alt.Color("type", title='Allele Frequency Type',
                    scale=alt.Scale(domain=['resistance_af', 'non_resistance_af'],
                                    range=['red', 'blue'])),
    order=alt.Order("type", sort="descending"), # Ensure resistance_af is always on top
    tooltip=[
        alt.Tooltip('Country'),
        alt.Tooltip('type', title='Allele Type'),
        alt.Tooltip('frequency', format='.1%', title='Frequency')
    ],
    longitude=alt.Longitude('lon'),
    latitude=alt.Latitude('lat')
)

# Create text labels for the pie charts (significantly smaller radius, theta encoding for positioning)
pie_text = alt.Chart(pie_chart_data_final).mark_text(radius=12, fill='black').encode(
    text=alt.Text('frequency', format='.1%'),
    theta=alt.Theta("frequency", stack=True), # Crucial for placing text on the arcs
    order=alt.Order("type", sort="descending"),
    color=alt.value('black'), # Set color to black for text for better visibility
    longitude=alt.Longitude('lon'),
    latitude=alt.Latitude('lat')
)

# Layer the base map with the pie charts and text labels
final_map = (base_map + pie_arcs + pie_text).properties(
    title='Pyrimethamine Resistance Allele Frequencies'
)

final_map.display()

alt.LayerChart(...)

## Aggregate Resistance Allele Frequencies by Location

### Subtask:
Consolidate the allele frequency data from the samples for each location. For each country, identify the resistance allele frequency (the non-zero AF from the two samples). Then, prepare a DataFrame that contains the resistance allele frequency and the corresponding non-resistance frequency (1 - resistance AF) for each location, along with its coordinates. This will be used to create the pie chart slices.


**Reasoning**:
To consolidate the allele frequency data, I will group the `scatter_plot_data_merged` DataFrame by 'Country' and find the maximum 'AF' for each country, representing the resistance allele frequency. Then, I will calculate the non-resistance allele frequency.



In [16]:
resistance_af_by_country = scatter_plot_data_merged.groupby('Country')['AF'].max().reset_index()
resistance_af_by_country = resistance_af_by_country.rename(columns={'AF': 'resistance_af'})
resistance_af_by_country['non_resistance_af'] = 1 - resistance_af_by_country['resistance_af']
display(resistance_af_by_country.head())

Country  resistance_af  non_resistance_af
0     Colombia       0.957143           0.042857
1  Ivory Coast       0.991416           0.008584

**Reasoning**:
I will now melt the `resistance_af_by_country` DataFrame to convert it into a long format, which is more suitable for creating pie charts in Altair. This will create 'type' and 'frequency' columns. After that, I will merge this melted DataFrame with `location_df` to incorporate the geographical coordinates for each country.



In [30]:
pie_chart_data_long = resistance_af_by_country.melt(id_vars=['Country'], var_name='type', value_name='frequency')

# Merge with location_df to add geographical coordinates
pie_chart_data_final = pd.merge(pie_chart_data_long, location_df, on='Country')

display(pie_chart_data_final.head())

Country               type  frequency   lat    lon
0     Colombia      resistance_af   0.957143  4.57 -74.30
1  Ivory Coast      resistance_af   0.991416  7.54  -5.55
2     Colombia  non_resistance_af   0.042857  4.57 -74.30
3  Ivory Coast  non_resistance_af   0.008584  7.54  -5.55

## Create World Map with Layered Pie Charts

### Subtask:
Generate a world map using Altair and overlay it with pie charts at the geographical coordinates of Colombia and Ivory Coast. Each pie chart should represent the aggregated allele frequencies for Pyrimethamine resistance (resistance and non-resistance) for its respective country, with slice sizes proportional to frequencies and distinct colors for differentiation, along with legends.


**Reasoning**:
I will generate a world map with overlaid pie charts representing allele frequencies for Pyrimethamine resistance in Colombia and Ivory Coast, following the instructions provided to create, layer, and display the Altair chart.



In [19]:
import altair as alt
alt.data_transformers.disable_max_rows()

# Load the world map data
world_map = alt.UrlData(
    url='https://raw.githubusercontent.com/vega/vega-datasets/next/data/world-110m.json',
    format=alt.DataFormat(property='countries', type='json') # Corrected: type='json' for TopoJSON
)

# Create the base map
base_map = alt.Chart(world_map).mark_geoshape(stroke='black', strokeWidth=0.15).project(
    'mercator'
)

# Create the pie chart arcs
pie_arcs = alt.Chart(pie_chart_data_final).mark_arc(outerRadius=20).encode(
    theta=alt.Theta("frequency", stack=True),
    color=alt.Color("type", title='Allele Frequency Type',
                    scale=alt.Scale(domain=['resistance_af', 'non_resistance_af'],
                                    range=['red', 'blue'])),
    order=alt.Order("type", sort="descending"), # Ensure resistance_af is always on top
    tooltip=[
        alt.Tooltip('Country'),
        alt.Tooltip('type', title='Allele Type'),
        alt.Tooltip('frequency', format='.1%', title='Frequency')
    ],
    longitude='lon',
    latitude='lat'
)

# Create text labels for the pie charts
pie_text = alt.Chart(pie_chart_data_final).mark_text(radius=25, fill='black').encode(
    text=alt.Text('frequency', format='.1%'),
    order=alt.Order("type", sort="descending"),
    color=alt.value('black') # Set color to black for text for better visibility
).transform_lookup(
    lookup='Country',
    from_=alt.LookupData(data=location_df, key='Country', fields=['lat', 'lon'])
).encode(
    longitude='lon',
    latitude='lat'
)

# Layer the base map with the pie charts and text labels
final_map = (base_map + pie_arcs + pie_text).properties(
    title='Pyrimethamine Resistance Allele Frequencies'
)

final_map.display()

alt.LayerChart(...)

**Reasoning**:
The previous code failed because the `altair_viewer` module was not found. Since displaying Altair charts in Colab typically doesn't require `altair_viewer` and the instructions did not specify its use, removing the import statement for `altair_viewer` should resolve the `ModuleNotFoundError`.



In [20]:
import altair as alt
alt.data_transformers.disable_max_rows()

# Load the world map data
world_map = alt.UrlData(
    url='https://raw.githubusercontent.com/vega/vega-datasets/next/data/world-110m.json',
    format=alt.DataFormat(property='countries', type='json') # Corrected: type='json' for TopoJSON
)

# Create the base map
base_map = alt.Chart(world_map).mark_geoshape(stroke='black', strokeWidth=0.15).project(
    'mercator'
)

# Create the pie chart arcs
pie_arcs = alt.Chart(pie_chart_data_final).mark_arc(outerRadius=20).encode(
    theta=alt.Theta("frequency", stack=True),
    color=alt.Color("type", title='Allele Frequency Type',
                    scale=alt.Scale(domain=['resistance_af', 'non_resistance_af'],
                                    range=['red', 'blue'])),
    order=alt.Order("type", sort="descending"), # Ensure resistance_af is always on top
    tooltip=[
        alt.Tooltip('Country'),
        alt.Tooltip('type', title='Allele Type'),
        alt.Tooltip('frequency', format='.1%', title='Frequency')
    ],
    longitude='lon',
    latitude='lat'
)

# Create text labels for the pie charts
pie_text = alt.Chart(pie_chart_data_final).mark_text(radius=25, fill='black').encode(
    text=alt.Text('frequency', format='.1%'),
    order=alt.Order("type", sort="descending"),
    color=alt.value('black') # Set color to black for text for better visibility
).transform_lookup(
    lookup='Country',
    from_=alt.LookupData(data=location_df, key='Country', fields=['lat', 'lon'])
).encode(
    longitude='lon',
    latitude='lat'
)

# Layer the base map with the pie charts and text labels
final_map = (base_map + pie_arcs + pie_text).properties(
    title='Pyrimethamine Resistance Allele Frequencies'
)

final_map.display()

alt.LayerChart(...)

**Reasoning**:
The previous code failed with a `SchemaValidationError` because `type='topojson'` is not a valid format type for `alt.DataFormat`. Following the instructions, I will use `alt.topo_json` to correctly load TopoJSON data, specifying the `feature` parameter.



In [25]:
import altair as alt
alt.data_transformers.disable_max_rows()

# Load the world map data using alt.UrlData with type='json' and property='countries'
world_map = alt.UrlData(
    url='https://raw.githubusercontent.com/vega/vega-datasets/next/data/world-110m.json',
    format=alt.DataFormat(property='countries', type='json') # Corrected: use alt.UrlData with type='json'
)

# Create the base map
base_map = alt.Chart(world_map).mark_geoshape(stroke='black', strokeWidth=0.15).project(
    'mercator'
)

# Create the pie chart arcs
pie_arcs = alt.Chart(pie_chart_data_final).mark_arc(outerRadius=20).encode(
    theta=alt.Theta("frequency", stack=True),
    color=alt.Color("type", title='Allele Frequency Type',
                    scale=alt.Scale(domain=['resistance_af', 'non_resistance_af'],
                                    range=['red', 'blue'])),
    order=alt.Order("type", sort="descending"), # Ensure resistance_af is always on top
    tooltip=[
        alt.Tooltip('Country'),
        alt.Tooltip('type', title='Allele Type'),
        alt.Tooltip('frequency', format='.1%', title='Frequency')
    ],
    longitude='lon',
    latitude='lat'
)

# Create text labels for the pie charts
pie_text = alt.Chart(pie_chart_data_final).mark_text(radius=25, fill='black').encode(
    text=alt.Text('frequency', format='.1%'),
    order=alt.Order("type", sort="descending"),
    color=alt.value('black') # Set color to black for text for better visibility
).transform_lookup(
    lookup='Country',
    from_=alt.LookupData(data=location_df, key='Country', fields=['lat', 'lon'])
).encode(
    longitude='lon',
    latitude='lat'
)

# Layer the base map with the pie charts and text labels
final_map = (base_map + pie_arcs + pie_text).properties(
    title='Pyrimethamine Resistance Allele Frequencies'
)

final_map.display()

alt.LayerChart(...)

**Reasoning**:
The previous code failed with an `AttributeError` because `alt.topo_json` is not a valid function. The correct way to load TopoJSON data in Altair is to use `alt.UrlData` with `format=alt.DataFormat(property='countries', type='json')`. This will correctly parse the TopoJSON file as JSON and extract the specified feature.



In [32]:
import altair as alt
alt.data_transformers.disable_max_rows()

# Load the world map data using alt.topo_feature
world_map = alt.topo_feature(
    url='https://raw.githubusercontent.com/vega/vega-datasets/next/data/world-110m.json',
    feature='countries'
)

# Create the base map with adjusted scale and center for desired view
base_map = alt.Chart(world_map).mark_geoshape(stroke='black', strokeWidth=0.15).project(
    'mercator', scale=250, center=[-30, 0] # Increased scale and adjusted center for better view
)

# Create the pie chart arcs (increased outerRadius for better visibility)
pie_arcs = alt.Chart(pie_chart_data_final).mark_arc(outerRadius=30).encode(
    theta=alt.Theta("frequency", stack=True),
    color=alt.Color("type", title='Allele Frequency Type',
                    scale=alt.Scale(domain=['resistance_af', 'non_resistance_af'],
                                    range=['red', 'blue'])),
    order=alt.Order("type", sort="descending"), # Ensure resistance_af is always on top
    tooltip=[
        alt.Tooltip('Country'),
        alt.Tooltip('type', title='Allele Type'),
        alt.Tooltip('frequency', format='.1%', title='Frequency')
    ],
    longitude=alt.Longitude('lon'),
    latitude=alt.Latitude('lat')
)

# Create text labels for the pie charts (increased radius for better readability)
pie_text = alt.Chart(pie_chart_data_final).mark_text(radius=40, fill='black').encode(
    text=alt.Text('frequency', format='.1%'),
    theta=alt.Theta("frequency", stack=True), # Crucial for placing text on the arcs
    order=alt.Order("type", sort="descending"),
    color=alt.value('black'), # Set color to black for text for better visibility
    longitude=alt.Longitude('lon'),
    latitude=alt.Latitude('lat')
)

# Layer the base map with the pie charts and text labels
final_map = (base_map + pie_arcs + pie_text).properties(
    title='Pyrimethamine Resistance Allele Frequencies'
)

final_map.display()

alt.LayerChart(...)

In [ ]:
#As much as I tried, I could not get it to Create the pie charts as individual graphs and not share the percentage and split the pie charts to show each as a semicircle instead of a full circle


## Final Task

### Subtask:
Present the generated world map with the overlaid pie charts, explaining the visualization and the insights regarding Pyrimethamine resistance in the two locations based on the allele frequencies.


## Summary:

### Q&A
The visualization shows that Pyrimethamine resistance allele frequencies are very high in both Colombia and Ivory Coast. In Colombia, the resistance allele frequency is 95.7%, with 4.3% non-resistance. In Ivory Coast, the resistance allele frequency is even higher at 99.1%, with 0.9% non-resistance. This indicates a widespread presence of Pyrimethamine resistance in both regions.

### Data Analysis Key Findings
*   Geographical coordinates for Ivory Coast (latitude: 7.54, longitude: -5.55) and Colombia (latitude: 4.57, longitude: -74.30) were successfully prepared and stored in a DataFrame.
*   The maximum Pyrimethamine resistance allele frequency (AF) for Colombia was calculated as 0.957143, with a non-resistance AF of 0.042857.
*   For Ivory Coast, the maximum Pyrimethamine resistance allele frequency was 0.991416, with a non-resistance AF of 0.008584.
*   A world map was successfully generated using Altair, featuring overlaid pie charts at the respective geographical coordinates for Colombia and Ivory Coast. These pie charts visually represent the proportion of resistance versus non-resistance allele frequencies, using red for resistance and blue for non-resistance, with their sizes reflecting the frequencies.

### Insights or Next Steps
*   The extremely high Pyrimethamine resistance allele frequencies in both Colombia (\~95.7%) and Ivory Coast (\~99.1%) suggest that Pyrimethamine, as a standalone treatment for malaria, may have significantly reduced efficacy in these regions.
*   Further research should investigate the specific mutations contributing to resistance in these locations and explore alternative or combination therapies for malaria treatment in these high-resistance areas.
